# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements_Dengo.txt
        pip install -r requirements_Type2.txt
    - name: Package
      run: |
        pyinstaller JRESim_Dengo.py --onefile --name JRESim_Dengo_${{ github.ref_name }}
        pyinstaller JRESim_Type2.py --onefile --name JRESim_Type2_${{ github.ref_name }}
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/JRESim_*.exe
